tap "homebrew/bundle"

brew "fd"
brew "fzf"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "anki"
cask "firefox"
cask "font-0xproto-nerd-font"
cask "iterm2"
cask "obsidian"
cask "spotify"
cask "vlc"
