tap "homebrew/bundle"
tap "homebrew/core"

brew "fd"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
